on:
  push:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4.2.2
      - run: pwsh -File generate_readme.ps1
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Tashi
      
